apiVersion: apps/v1.1
kind: Deployment
metadata:
  name: webapp11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp11
  template:
    metadata:
      labels:
        app: webapp11
    spec:
      containers:
      - name: httpd
        image: httpd:2.4
        ports:
        - containerPort: 80

        volumeMounts:
        - name: html
          mountPath: /usr/local/apache2/htdocs/index.html
          subPath: index.html

      volumes:
      - name: html
        configMap:
          name: webapp11-html